on:
  pull_request:
    types:
      - closed

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-staging-env
        secrets: inherit

      # there is a bug with the actions/cache used in bahmutov/npm-install@v1 on "closed" event
      # more infos here : https://github.com/actions/cache/issues/478
      - run: yarn --frozen-lockfile
        working-directory: .cdk

      # Interestingly, `cdk` uses a hash of the directory path, and if it doesn't exist, it can't hash it.
      - name: lol wut? don't look at this.
        run: mkdir public

      - name: Destroy the stack on AWS
        run: yarn destroy
        working-directory: .cdk

      - name: Delete the github deployments and the corresponding environment
        uses: strumwolf/delete-deployment-environment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ env.STAGE }}
