on: pull_request

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create Deployment
      uses: bobheadxi/deployments@v1
      id: deployment
      with:
        step: start
        env: ${{ env.STAGE }}
        ref: ${{ github.head_ref }}
        no_override: false
        transient: true

    - uses: actions/checkout@v3
    - uses: ./.github/actions/dry
      secrets: inherit
    - uses: ./.github/actions/setup-aws
      secrets: inherit

    - uses: teaxyz/setup@v0
      with:
        action: build

    - name: Apply Staging Configuration
      run: |
        sed -i -e 's/^baseURL\s*=.*$/baseUrl = ""/i' config.toml
        echo "relativeurls = true" >>config.toml
      working-directory: src

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: .cdk

    - name: Deploy to AWS
      id: cdk_deploy
      run: yarn deploy
      working-directory: .cdk

    - name: Seal Deployment
      uses: bobheadxi/deployments@v1
      if: always()
      with:
        step: finish
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env: ${{ env.STAGE }}
        env_url: ${{ steps.cdk_deploy.outputs.env_url }}
